# Generated by Django 5.2.3 on 2026-06-26 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiafeLogConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(choices=[('nota_empenho', 'Nota de Empenho'), ('saldo_orcamentario', 'Saldo Orcamentario'), ('saldo_contabil', 'Saldo Contabil'), ('acoes', 'Acoes de Governo'), ('natureza_despesa', 'Natureza de Despesa'), ('credores', 'Credores'), ('programas', 'Programas'), ('contratos_convenios', 'Contratos e Convenios'), ('exec_orcamentaria', 'Execucao Orcamentaria'), ('exec_financeira', 'Execucao Financeira'), ('fatos_contratos', 'Fatos de Contratos'), ('planejamento_loa', 'Planejamento LOA'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('parametros', models.JSONField(default=dict, help_text='Parametros enviados na consulta')),
                ('status_http', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('erro_detalhe', models.TextField(blank=True)),
                ('tempo_resposta_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consultado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siafe_consultas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Consulta SIAFE',
                'verbose_name_plural': 'Logs de Consultas SIAFE',
                'ordering': ['-criado_em'],
            },
        ),
    ]
