# Generated by Django 6.0.6 on 2026-06-23 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoLicitatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=30)),
                ('ano', models.PositiveSmallIntegerField()),
                ('numero_sei', models.CharField(blank=True, max_length=30)),
                ('modalidade', models.CharField(choices=[('pregao', 'Pregão'), ('concorrencia', 'Concorrência'), ('dispensa', 'Dispensa'), ('inexigibilidade', 'Inexigibilidade'), ('concurso', 'Concurso'), ('leilao', 'Leilão'), ('dialogo_competitivo', 'Diálogo Competitivo')], max_length=25)),
                ('objeto', models.TextField()),
                ('is_srp', models.BooleanField(default=False, help_text='Conduzido por Sistema de Registro de Preços')),
                ('status', models.CharField(choices=[('em_preparacao', 'Em preparação'), ('publicado', 'Publicado'), ('em_julgamento', 'Em julgamento'), ('homologado', 'Homologado'), ('revogado', 'Revogado'), ('anulado', 'Anulado'), ('fracassado', 'Fracassado'), ('deserto', 'Deserto')], default='em_preparacao', max_length=20)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('data_homologacao', models.DateField(blank=True, null=True)),
                ('pncp_id', models.CharField(blank=True, max_length=100)),
                ('publicado_pncp', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos_licitatorios', to='core.orgao')),
            ],
            options={
                'verbose_name': 'Processo Licitatório',
                'unique_together': {('orgao', 'numero_processo', 'ano')},
            },
        ),
    ]
