# Generated by Django 5.2.3 on 2026-06-29 23:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoLicitatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edital', models.CharField(db_index=True, default='', max_length=50, verbose_name='Número do Edital/Aviso')),
                ('numero_controle_pncp', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Número de Controle PNCP')),
                ('numero_compra_api', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Compra Compras.gov')),
                ('ano', models.PositiveIntegerField(default=2026, verbose_name='Ano')),
                ('modalidade', models.CharField(choices=[('pregao_eletronico', 'Pregão Eletrônico'), ('pregao_presencial', 'Pregão Presencial'), ('concorrencia_eletronica', 'Concorrência Eletrônica'), ('concorrencia_presencial', 'Concorrência Presencial'), ('concurso', 'Concurso'), ('dispensa', 'Dispensa de Licitação'), ('inexigibilidade', 'Inexigibilidade'), ('outros', 'Outras Modalidades')], default='pregao_eletronico', max_length=30, verbose_name='Modalidade')),
                ('situacao', models.CharField(blank=True, default='Publicado', max_length=50, verbose_name='Situação')),
                ('objeto', models.TextField(verbose_name='Objeto')),
                ('processo_sei', models.CharField(blank=True, max_length=100, verbose_name='Processo Administrativo/SEI')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Estimado (R$)')),
                ('valor_homologado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Homologado (R$)')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('data_homologacao', models.DateField(blank=True, null=True, verbose_name='Data de Homologação/Atualização')),
                ('link_pncp', models.URLField(blank=True, max_length=500, verbose_name='Link PNCP')),
                ('lei', models.CharField(default='Lei 14.133/2021', max_length=50, verbose_name='Amparo Legal / Lei')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Processo Licitatório',
                'verbose_name_plural': 'Processos Licitatórios',
                'ordering': ['-ano', '-data_publicacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemLicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField(verbose_name='Número do Item')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('unidade', models.CharField(blank=True, max_length=50, verbose_name='Unidade')),
                ('quantidade', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='Quantidade')),
                ('valor_unitario_estimado', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='Valor Unit. Estimado (R$)')),
                ('valor_unitario_homologado', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='Valor Unit. Homologado (R$)')),
                ('fornecedor_vencedor', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor Vencedor')),
                ('cnpj_vencedor', models.CharField(blank=True, max_length=20, verbose_name='CNPJ Vencedor')),
                ('licitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='licitacao.processolicitatorio')),
            ],
            options={
                'verbose_name': 'Item de Licitação',
                'verbose_name_plural': 'Itens de Licitação',
                'ordering': ['numero_item'],
            },
        ),
    ]
