# Generated by Django 5.2.3 on 2026-08-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processolicitatorio',
            name='modalidade',
            field=models.CharField(choices=[('pregao_eletronico', 'Pregão Eletrônico'), ('pregao_presencial', 'Pregão Presencial'), ('concorrencia_eletronica', 'Concorrência Eletrônica'), ('concorrencia_presencial', 'Concorrência Presencial'), ('concurso', 'Concurso'), ('credenciamento', 'Credenciamento'), ('dispensa', 'Dispensa de Licitação'), ('inexigibilidade', 'Inexigibilidade'), ('outros', 'Outras Modalidades')], default='pregao_eletronico', max_length=30, verbose_name='Modalidade'),
        ),
    ]
