# Generated by Django 6.0.6 on 2026-06-23 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Ministério Público do Estado do Piauí', max_length=255)),
                ('sigla', models.CharField(default='MPPI', max_length=20)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('pncp_codigo_orgao', models.CharField(blank=True, max_length=50)),
                ('uf', models.CharField(default='PI', max_length=2)),
                ('esfera', models.CharField(default='estadual_mp', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Órgão',
            },
        ),
        migrations.CreateModel(
            name='UnidadeRequisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(choices=[('CPPT', 'CPPT — Coordenadoria de Patrimônio e Prestação de Contas'), ('CTI', 'CTI — Coordenadoria de Tecnologia da Informação'), ('CAA', 'CAA — Coordenadoria de Apoio Administrativo'), ('CRH', 'CRH — Coordenadoria de Recursos Humanos'), ('GSI', 'GSI — Gerência de Segurança Institucional'), ('CEAF', 'CEAF — Centro de Estudos e Aperfeiçoamento Funcional'), ('CI', 'CI — Coordenadoria de Infraestrutura'), ('CLC', 'CLC — Coordenadoria de Licitações e Contratos'), ('CCF', 'CCF — Coordenadoria de Contabilidade e Finanças'), ('APG', 'APG — Assessoria de Planejamento e Gestão'), ('GAECO', 'GAECO — Grupo de Atuação Especial Contra o Crime Organizado'), ('FPROCON', 'FPROCON — Fundo de Proteção ao Consumidor'), ('CCS', 'CCS — Coordenadoria de Comunicação Social')], max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.orgao')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidade Requisitante',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('requisitante', 'Requisitante (art. 7º Ato PGJ 1381/2024)'), ('area_tecnica', 'Área Técnica'), ('apg', 'APG — Assessoria de Planejamento e Gestão'), ('assessor_compras', 'Assessor de Compras / Agente de Contratação'), ('equipe_apoio', 'Equipe de Apoio (Ato PGJ 1414/2024)'), ('comissao', 'Membro de Comissão de Contratação'), ('appl', 'APPL — Assessoria para Pareceres em Processos Licitatórios'), ('gestor_contrato', 'Gestor de Contrato'), ('fiscal_adm', 'Fiscal Administrativo'), ('fiscal_tecnico', 'Fiscal Técnico'), ('fiscal_requisitante', 'Fiscal Requisitante (TI — Res. CNMP 283/2024)'), ('int_requisitante_ti', 'Integrante Requisitante TI (Res. CNMP 283/2024)'), ('int_tecnico_ti', 'Integrante Técnico TI (Res. CNMP 283/2024)'), ('int_administrativo_ti', 'Integrante Administrativo TI (Res. CNMP 283/2024)'), ('autoridade', 'Autoridade Competente (PGJ ou delegado)'), ('auditor', 'Auditor Interno')], max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidaderequisitante')),
            ],
            options={
                'verbose_name': 'Perfil de Acesso',
                'unique_together': {('usuario', 'orgao', 'perfil')},
            },
        ),
    ]
