# Generated by Django 5.2.3 on 2026-06-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_unidades_requisitantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidaderequisitante',
            name='sigla',
            field=models.CharField(choices=[('CPPT', 'CPPT — Coordenadoria de Perícias e Pareceres Técnicos'), ('CTI', 'CTI — Coordenadoria de Tecnologia da Informação'), ('CAA', 'CAA — Coordenadoria de Apoio Administrativo'), ('CRH', 'CRH — Coordenadoria de Recursos Humanos'), ('GSI', 'GSI — Gerência de Segurança Institucional'), ('CEAF', 'CEAF — Centro de Estudos e Aperfeiçoamento Funcional'), ('CI', 'CI — Coordenadoria de Infraestrutura'), ('CLC', 'CLC — Coordenadoria de Licitações e Contratos'), ('CCF', 'CCF — Coordenadoria de Contabilidade e Finanças'), ('APG', 'APG — Assessoria de Planejamento e Gestão'), ('CONINT', 'CONINT — Controle Interno'), ('GAECO', 'GAECO — Grupo de Atuação Especial Contra o Crime Organizado'), ('FPROCON', 'FPROCON — Fundo de Proteção ao Consumidor'), ('CCS', 'CCS — Coordenadoria de Comunicação Social')], max_length=20),
        ),
    ]
