# Generated by Django 5.2.3 on 2026-08-14 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_conint_unidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('mensagem', models.TextField(max_length=500)),
                ('tipo', models.CharField(choices=[('info', 'Informativo'), ('alerta', 'Alerta'), ('prazo', 'Prazo'), ('sucesso', 'Sucesso')], default='info', max_length=15)),
                ('url_destino', models.CharField(blank=True, help_text='Link opcional para a tela relacionada (ex: /contratos/vencimentos/).', max_length=300)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('unidade_destino', models.ForeignKey(blank=True, help_text='Deixe em branco para enviar a todos os usuários.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.unidaderequisitante')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ('-criada_em',),
            },
        ),
        migrations.CreateModel(
            name='NotificacaoLida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida_em', models.DateTimeField(auto_now_add=True)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='core.notificacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_lidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leitura de Notificação',
                'verbose_name_plural': 'Leituras de Notificações',
            },
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['ativa', '-criada_em'], name='core_notifi_ativa_50e7c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificacaolida',
            unique_together={('notificacao', 'usuario')},
        ),
    ]
