# Generated by Django 6.0.6 on 2026-06-23 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sei', models.CharField(blank=True, help_text='Número do processo SEI/MPPI', max_length=30)),
                ('numero_etp', models.CharField(max_length=30)),
                ('is_ti', models.BooleanField(default=False, help_text='Contratação de TIC — aplica Res. CNMP 283/2024')),
                ('necessidade_contratacao', models.TextField()),
                ('requisitos_contratacao', models.TextField()),
                ('levantamento_mercado', models.TextField()),
                ('descricao_solucao', models.TextField()),
                ('estimativa_quantidade', models.TextField()),
                ('estimativa_custo', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('justificativa_parcelamento', models.TextField()),
                ('contratacoes_correlatas', models.TextField(blank=True)),
                ('alinhamento_pca', models.TextField(help_text='Vinculação com o PCA vigente')),
                ('resultados_pretendidos', models.TextField()),
                ('providencias_previas', models.TextField(blank=True)),
                ('impactos_ambientais', models.TextField(help_text='Art. 11, I, NLLC — sustentabilidade')),
                ('declaracao_viabilidade', models.BooleanField(default=False)),
                ('tco_total', models.DecimalField(blank=True, decimal_places=2, help_text='TCO — Total Cost of Ownership (art. 10, Res. CNMP 283/2024)', max_digits=16, null=True)),
                ('solucao_em_outros_orgaos', models.TextField(blank=True, help_text='Res. CNMP 283/2024, art. 10 — levantamento de mercado TI')),
                ('software_livre_avaliado', models.BooleanField(default=False)),
                ('gerado_por_ia', models.BooleanField(default=False)),
                ('ia_modelo_utilizado', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_revisao', 'Em revisão'), ('aprovado', 'Aprovado')], default='rascunho', max_length=15)),
                ('etp_dispensado', models.BooleanField(default=False)),
                ('fundamento_dispensa_etp', models.CharField(blank=True, help_text='Ex: art. 75, I, Lei 14.133/2021 — abaixo do limite', max_length=200)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ia_revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etps_revisados', to=settings.AUTH_USER_MODEL)),
                ('item_pca', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etp_origem', to='pca.itempca')),
            ],
        ),
        migrations.CreateModel(
            name='EquipePlanejamentoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lider', models.CharField(choices=[('requisitante', 'Requisitante'), ('tecnico', 'Técnico'), ('administrativo', 'Administrativo')], default='requisitante', help_text='Preferencialmente o Requisitante — art. 9º Res. CNMP 283/2024', max_length=20)),
                ('ato_designacao_sei', models.CharField(blank=True, max_length=30)),
                ('integrante_administrativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ep_administrativo', to=settings.AUTH_USER_MODEL)),
                ('integrante_requisitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ep_requisitante', to=settings.AUTH_USER_MODEL)),
                ('integrante_tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ep_tecnico', to=settings.AUTH_USER_MODEL)),
                ('etp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_planejamento_ti', to='planejamento.etp')),
            ],
        ),
        migrations.CreateModel(
            name='MatrizRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_atual', models.CharField(choices=[('planejamento', 'Planejamento'), ('selecao', 'Seleção'), ('gestao', 'Gestão')], default='planejamento', max_length=20)),
                ('etp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matriz_risco', to='planejamento.etp')),
            ],
        ),
        migrations.CreateModel(
            name='RiscoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_risco', models.TextField()),
                ('causa', models.TextField()),
                ('consequencia', models.TextField()),
                ('probabilidade', models.PositiveSmallIntegerField(choices=[(1, 'Muito baixa'), (2, 'Baixa'), (3, 'Média'), (4, 'Alta'), (5, 'Muito alta')])),
                ('impacto', models.PositiveSmallIntegerField(choices=[(1, 'Muito baixo'), (2, 'Baixo'), (3, 'Médio'), (4, 'Alto'), (5, 'Muito alto')])),
                ('nivel_risco', models.PositiveSmallIntegerField(editable=False)),
                ('responsavel', models.CharField(choices=[('adm', 'Administração'), ('contratado', 'Contratado'), ('compartilhado', 'Compartilhado')], max_length=20)),
                ('acao_preventiva', models.TextField()),
                ('acao_contingencia', models.TextField()),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='planejamento.matrizrisco')),
            ],
        ),
        migrations.CreateModel(
            name='TermoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sei', models.CharField(blank=True, max_length=30)),
                ('objeto', models.TextField()),
                ('fundamentacao_legal', models.TextField(help_text='Inclui referência ao ETP e normativos aplicáveis ao MPPI')),
                ('descricao_solucao', models.TextField()),
                ('requisitos_habilitacao', models.TextField()),
                ('criterio_julgamento', models.CharField(choices=[('menor_preco', 'Menor Preço'), ('maior_desconto', 'Maior Desconto'), ('melhor_tecnica', 'Melhor Técnica e Preço'), ('maior_retorno', 'Maior Retorno Econômico')], max_length=30)),
                ('prazo_execucao', models.PositiveIntegerField(help_text='Em dias')),
                ('local_execucao', models.TextField()),
                ('obrigacoes_contratante', models.TextField()),
                ('obrigacoes_contratado', models.TextField()),
                ('criterios_medicao', models.TextField()),
                ('is_servico_continuo', models.BooleanField(default=False)),
                ('prazo_inicial_meses', models.PositiveSmallIntegerField(blank=True, help_text='Mín. 24 meses para serviços contínuos — art. 5º Ato 1415/2024', null=True)),
                ('prazo_maximo_meses', models.PositiveSmallIntegerField(blank=True, help_text='Máx. 120 meses (prazo decenal)', null=True)),
                ('is_srp', models.BooleanField(default=False)),
                ('justificativa_srp', models.TextField(blank=True)),
                ('modalidade_remuneracao_ti', models.CharField(blank=True, choices=[('pontos_funcao', 'Pontos de função + horas'), ('sprint', 'Valor fixo por sprint'), ('alocacao', 'Alocação vinculada a resultados'), ('fixo_mensal', 'Valor fixo mensal por sistema'), ('fixo_alocacao', 'Fixo por alocação com resultados')], max_length=30)),
                ('vedacoes_ti_observadas', models.BooleanField(default=False, help_text='Confirmação de que as vedações do art. 19 Res. CNMP 283/2024 foram observadas')),
                ('gerado_por_ia', models.BooleanField(default=False)),
                ('modelo_agu_base', models.CharField(blank=True, help_text='Modelo AGU utilizado como base (Ato PGJ 1413/2024)', max_length=100)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_revisao', 'Em revisão'), ('appl', 'Aguardando análise APPL'), ('aprovado', 'Aprovado'), ('publicado', 'Publicado')], default='rascunho', max_length=15)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('etp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termo_referencia', to='planejamento.etp')),
            ],
        ),
    ]
