# Generated by Django 5.2.3 on 2026-08-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0017_remove_itempca_etp'),
        ('planejamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etp',
            name='item_pca',
        ),
        migrations.CreateModel(
            name='LoteContratacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text="Rótulo interno do agrupamento, ex: 'Lote 1 — Material de expediente'.", max_length=60)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('itens', models.ManyToManyField(related_name='lotes_contratacao', to='pca.itempca')),
                ('pca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_contratacao', to='pca.planocontratacaoanual')),
            ],
            options={
                'verbose_name': 'Lote de Contratação (instrução)',
                'verbose_name_plural': 'Lotes de Contratação (instrução)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='etp',
            name='lote',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='etp', to='planejamento.lotecontratacao'),
            preserve_default=False,
        ),
    ]
