# Generated by Django 5.2.3 on 2026-08-17 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0017_remove_itempca_etp'),
        ('planejamento', '0002_remove_etp_item_pca_lotecontratacao_etp_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etp',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='equipeplanejamentoti',
            name='etp',
        ),
        migrations.CreateModel(
            name='DocumentoOficializacaoDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text="Rótulo interno do agrupamento, ex: 'Lote 1 — Material de expediente'.", max_length=60)),
                ('numero_sei', models.CharField(blank=True, help_text='Processo SEI Nº', max_length=30)),
                ('objeto', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aberto', 'Processo aberto'), ('cancelado', 'Cancelado')], default='rascunho', max_length=15)),
                ('unidade_orcamentaria', models.CharField(blank=True, choices=[('pgj', 'PGJ — Procuradoria-Geral de Justiça'), ('fmmpi', 'FMMPI — Fundo de Modernização do MPPI'), ('fprocon', 'FPROCON — Fundo do PROCON')], max_length=10)),
                ('natureza_objeto', models.CharField(blank=True, choices=[('servicos_nao_continuados', 'Serviços não continuados'), ('fornecimento_continuado', 'Fornecimento continuado'), ('fornecimento_nao_continuado', 'Fornecimento não continuado'), ('servicos_continuados_sem_demo', 'Serviços continuados sem dedicação de mão de obra'), ('servicos_continuados_com_demo', 'Serviços continuados com dedicação de mão de obra (DEMO)'), ('obras_servicos_engenharia', 'Obras e serviços de engenharia'), ('solucao_ti', 'Aquisição de solução de Tecnologia da Informação')], max_length=30)),
                ('contratacao_correlata', models.BooleanField(default=False, help_text='Há necessidade de contratação correlata (providências prévias)?')),
                ('contratacao_correlata_qual', models.TextField(blank=True, help_text='Se sim, qual?')),
                ('grau_prioridade', models.CharField(blank=True, choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=10)),
                ('previsao_inicio_execucao', models.DateField(blank=True, null=True)),
                ('previsao_termino_execucao', models.DateField(blank=True, null=True)),
                ('objetivos_estrategicos', models.TextField(blank=True, help_text='Objetivos estratégicos, conforme redação do PCA vigente.')),
                ('alinhamento_pdtic', models.TextField(blank=True, help_text="Ex.: 'Ação 3 — Meta 5'. Texto livre por ora (sem sub-tabela dedicada).")),
                ('necessidade_contratacao', models.TextField(blank=True, help_text='Qual a necessidade da contratação?')),
                ('motivacao_justificativa', models.TextField(blank=True, help_text='Por que fazer a contratação (motivação/justificativa)?')),
                ('objetivo_contratacao', models.TextField(blank=True, help_text='Qual o objetivo da contratação?')),
                ('meta_contratacao', models.TextField(blank=True, help_text='Qual a meta a ser alcançada com a contratação?')),
                ('indicador_resultado', models.TextField(blank=True, help_text='Qual o indicador (resultado alcançado)?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('itens', models.ManyToManyField(related_name='documentos_oficializacao', to='pca.itempca')),
                ('pca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_oficializacao', to='pca.planocontratacaoanual')),
                ('responsavel_preenchimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dods_preenchidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Oficialização da Demanda (DOD)',
                'verbose_name_plural': 'Documentos de Oficialização da Demanda (DOD)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='equipeplanejamentoti',
            name='dod',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_planejamento_ti', to='planejamento.documentooficializacaodemanda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etp',
            name='dod',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='etp', to='planejamento.documentooficializacaodemanda'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LoteContratacao',
        ),
    ]
