# Generated by Django 5.2.3 on 2026-08-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0003_remove_etp_lote_remove_equipeplanejamentoti_etp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentooficializacaodemanda',
            name='unidade_orcamentaria',
            field=models.CharField(blank=True, choices=[('pgj', 'PGJ — Procuradoria-Geral de Justiça'), ('fmmpi', 'FMMPI — Fundo de Modernização do MPPI'), ('fpdc', 'FPDC — Fundo Estadual de Proteção e Defesa do Consumidor')], max_length=10),
        ),
    ]
