# Generated by Django 5.2.3 on 2026-08-17 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0004_alter_documentooficializacaodemanda_unidade_orcamentaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipeplanejamentoti',
            name='integrante_administrativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ep_administrativo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipeplanejamentoti',
            name='integrante_requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ep_requisitante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipeplanejamentoti',
            name='integrante_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ep_tecnico', to=settings.AUTH_USER_MODEL),
        ),
    ]
