# Generated by Django 5.2.3 on 2026-08-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0005_alter_equipeplanejamentoti_integrante_administrativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentooficializacaodemanda',
            name='com_demo',
            field=models.BooleanField(default=False, help_text='Só se aplica a serviços.', verbose_name='Com dedicação de mão de obra (DEMO)'),
        ),
        migrations.AddField(
            model_name='documentooficializacaodemanda',
            name='item_continuado',
            field=models.BooleanField(default=False, help_text='Serviço ou fornecimento contínuo, nos termos do Ato PGJ 1415/2024.', verbose_name='Item continuado'),
        ),
        migrations.AddField(
            model_name='documentooficializacaodemanda',
            name='solucao_tic',
            field=models.BooleanField(default=False, help_text='Contratação de solução de Tecnologia da Informação e Comunicação (Res. CNMP 283/2024) — exige equipe de planejamento com os 3 papéis.', verbose_name='Solução de TIC'),
        ),
        migrations.AlterField(
            model_name='documentooficializacaodemanda',
            name='natureza_objeto',
            field=models.CharField(blank=True, choices=[('servicos', 'Serviços'), ('fornecimento', 'Fornecimentos'), ('obra_engenharia', 'Obras e serviços de engenharia')], max_length=30),
        ),
    ]
