# Generated by Django 6.0.6 on 2026-06-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tipo_contratacao', models.CharField(max_length=30)),
                ('situacao', models.CharField(choices=[('dispensado', 'Dispensado — Ato PGJ 1383/2024'), ('obrigatorio', 'Obrigatório — exige manifestação APPL'), ('pendente', 'Pendente de análise'), ('manifestacao_emitida', 'Manifestação emitida pela APPL'), ('aprovado', 'Aprovado pela APPL'), ('reprovado', 'Reprovado pela APPL')], max_length=25)),
                ('fundamento_dispensa', models.TextField(blank=True, help_text='Ex: art. 75, I — R$ X < R$ 50.000 — Ato PGJ 1383/2024')),
                ('numero_parecer_appl', models.CharField(blank=True, max_length=30)),
                ('data_manifestacao', models.DateField(blank=True, null=True)),
                ('parecer_appl', models.TextField(blank=True)),
                ('numero_sei_parecer', models.CharField(blank=True, max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestacaoJuridicoReferencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tema', models.CharField(choices=[('substituicao_marca', 'MJR 56/2025 — Substituição de Marca'), ('pagamento_indenizacao', 'MJR 66/2025 — Pagamento por Indenização'), ('adesao_arp', 'MJR 86/2025 — Adesão a ARP (Carona)'), ('dispensa_75_i_ii', 'MJR 92/2024 — Dispensa Art. 75 I e II'), ('prorrogacao_arp', 'MJR 95/2025 — Prorrogação de ARP')], max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('ementa', models.TextField()),
                ('conclusao', models.TextField()),
                ('fundamentos_legais', models.TextField()),
                ('numero_sei', models.CharField(blank=True, max_length=30)),
                ('data_publicacao', models.DateField()),
                ('vigente', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Manifestação Jurídico Referencial (MJR)',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
