# Generated by Django 6.0.6 on 2026-06-23 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juridico', '0001_initial'),
        ('planejamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlejuridico',
            name='etp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controle_juridico', to='planejamento.etp'),
        ),
    ]
