# Generated by Django 6.0.6 on 2026-06-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FontePreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pncp', 'PNCP — Portal Nacional de Contratações Públicas'), ('painel_precos', 'Painel de Preços Gov.br'), ('bec_pi', 'BEC-PI — Bolsa Eletrônica de Compras do Piauí'), ('sinapi', 'SINAPI'), ('contrato_similar', 'Contrato similar (até 1 ano)'), ('nfe', 'Nota Fiscal Eletrônica'), ('fornecedor', 'Cotação direta de fornecedor (mín. 3)'), ('midia_especializada', 'Mídia especializada / tabela aprovada'), ('outro', 'Outro')], max_length=25)),
                ('identificador', models.CharField(help_text='Número do contrato, URL, cotação, NF-e etc.', max_length=300)),
                ('data_referencia', models.DateField()),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('codigo_catmat_catser', models.CharField(blank=True, max_length=20)),
                ('unidade_medida', models.CharField(max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=14)),
                ('precos_coletados', models.JSONField(default=list, help_text='[{"fonte_id": 1, "preco_unitario": 10.50, "excluido": false, "motivo_exclusao": ""}]')),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('preco_mediana', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('preco_medio_saneado', models.DecimalField(decimal_places=2, help_text='Média após remoção de outliers — metodologia TCU', max_digits=14, null=True)),
                ('preco_referencia', models.DecimalField(decimal_places=2, help_text='Preço adotado como referência para a licitação', max_digits=14, null=True)),
                ('valor_total_estimado', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('justificativa_preco', models.TextField(blank=True)),
                ('tco_detalhamento', models.JSONField(blank=True, help_text='Componentes do TCO para contratações de TIC', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PesquisaPrecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sei', models.CharField(blank=True, max_length=30)),
                ('metodologia', models.TextField(help_text='Justificativa da metodologia — IN SEGES 65/2021, art. 5º')),
                ('normativo_base', models.CharField(default='IN SEGES 65/2021', max_length=50)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('aprovada', 'Aprovada')], default='em_andamento', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
