# Generated by Django 6.0.6 on 2026-06-23 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotacao', '0001_initial'),
        ('planejamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisaprecos',
            name='etp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_precos', to='planejamento.etp'),
        ),
        migrations.AddField(
            model_name='pesquisaprecos',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesquisas_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcotacao',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cotacao.pesquisaprecos'),
        ),
        migrations.AddField(
            model_name='fontepreco',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontes', to='cotacao.pesquisaprecos'),
        ),
    ]
