# Generated by Django 5.2.3 on 2026-06-24 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoContratacaoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('coleta', 'Coleta de demandas (10–30 jul)'), ('consolidacao', 'Consolidação CLC + APG (1–20 ago)'), ('aprovacao', 'Aguardando aprovação PGJ'), ('aprovado', 'Aprovado pelo PGJ'), ('publicado_pncp', 'Publicado no PNCP'), ('revisao_out', 'Em revisão (1–30 out)'), ('revisao_loa', 'Em revisão pós-LOA')], default='coleta', max_length=20)),
                ('prazo_coleta_inicio', models.DateField(blank=True, null=True)),
                ('prazo_coleta_fim', models.DateField(blank=True, null=True)),
                ('prazo_consolidacao_fim', models.DateField(blank=True, null=True)),
                ('prazo_aprovacao_fim', models.DateField(blank=True, null=True)),
                ('data_aprovacao_pgj', models.DateField(blank=True, null=True)),
                ('data_publicacao_pncp', models.DateTimeField(blank=True, null=True)),
                ('pncp_sequencial', models.CharField(blank=True, max_length=100)),
                ('observacoes_pgj', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano de Contratação Anual',
                'ordering': ['-exercicio'],
            },
        ),
        migrations.CreateModel(
            name='ConformidadeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_referencia_aprovado', models.BooleanField(default=False)),
                ('pesquisa_mercado', models.BooleanField(default=False)),
                ('pareceres_juridicos', models.BooleanField(default=False)),
                ('publicacao_edital', models.BooleanField(default=False)),
                ('atas_certame', models.BooleanField(default=False)),
                ('termo_homologacao', models.BooleanField(default=False)),
                ('termo_adjudicacao', models.BooleanField(default=False)),
                ('atos_autorizacao', models.BooleanField(default=False)),
                ('documentacao_fornecedor', models.BooleanField(default=False)),
                ('assinatura_contrato', models.BooleanField(default=False)),
                ('publicacao_contrato', models.BooleanField(default=False)),
                ('documento_aceite', models.BooleanField(default=False)),
                ('justificativa_vantajosidade', models.BooleanField(default=False)),
                ('declaracao_conformidade', models.BooleanField(default=False)),
                ('pesquisa_precos', models.BooleanField(default=False)),
                ('mapa_comparativo', models.BooleanField(default=False)),
                ('certidoes_habilitacao', models.BooleanField(default=False)),
                ('margem_calculo', models.BooleanField(default=False)),
                ('parecer_orcamentario_financeiro', models.BooleanField(default=False)),
                ('parecer_juridico_execucao', models.BooleanField(default=False)),
                ('parecer_conint', models.BooleanField(default=False)),
                ('oficio_autorizacao_empenho', models.BooleanField(default=False)),
                ('atualizar_certidoes', models.BooleanField(default=False)),
                ('termo_aditivo_apostilamento', models.BooleanField(default=False)),
                ('publicacoes_execucao', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('avaliado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conformidades_avaliadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conformidade do Item',
            },
        ),
        migrations.CreateModel(
            name='DocumentoFormalizacaoDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sei', models.CharField(blank=True, max_length=30)),
                ('numero_dfd', models.CharField(blank=True, max_length=30)),
                ('descricao_objeto', models.TextField()),
                ('justificativa', models.TextField()),
                ('prazo_necessidade', models.DateField()),
                ('grau_prioridade', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=10)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado ao setor de licitações'), ('aprovado', 'Aprovado'), ('devolvido', 'Devolvido para adequação')], default='rascunho', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('requisitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dfds_requisitados', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidaderequisitante')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('categoria', models.CharField(choices=[('material', 'Material (CATMAT)'), ('servico', 'Serviço (CATSER)'), ('obras', 'Obras e Serviços de Engenharia'), ('solucao_ti', 'Solução de TIC (Res. CNMP 283/2024)'), ('publicidade', 'Publicidade (Dec. 21.813/2023)')], max_length=20)),
                ('codigo_catmat_catser', models.CharField(blank=True, max_length=20)),
                ('unidade_fornecimento', models.CharField(max_length=30)),
                ('quantidade_estimada', models.DecimalField(decimal_places=4, max_digits=14)),
                ('descricao', models.TextField()),
                ('tipo_contratacao', models.CharField(choices=[('licitacao', 'Licitação'), ('dispensa', 'Contratação Direta — Dispensa'), ('inexigibilidade', 'Contratação Direta — Inexigibilidade'), ('adesao_arp', 'Adesão a ARP (Carona)'), ('renovacao_contrato', 'Renovação de Contrato'), ('renovacao_arp', 'Prorrogação de ARP')], max_length=25)),
                ('valor_unitario_estimado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_total_estimado', models.DecimalField(decimal_places=2, max_digits=16)),
                ('data_vencimento_contrato_anterior', models.DateField(blank=True, null=True)),
                ('data_pretendida_conclusao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('is_srp', models.BooleanField(default=False)),
                ('justificativa_srp', models.TextField(blank=True)),
                ('dfd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pca.documentoformalizacaodemanda')),
            ],
            options={
                'verbose_name': 'Item do PCA',
                'ordering': ['numero_item'],
            },
        ),
    ]
