# Generated by Django 5.2.3 on 2026-06-24 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pca', '0001_initial'),
        ('planejamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itempca',
            name='etp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pca', to='planejamento.etp'),
        ),
        migrations.AddField(
            model_name='itempca',
            name='item_dependente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependentes', to='pca.itempca'),
        ),
        migrations.AddField(
            model_name='conformidadeitem',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conformidade', to='pca.itempca'),
        ),
        migrations.AddField(
            model_name='planocontratacaoanual',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcas_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planocontratacaoanual',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao'),
        ),
        migrations.AddField(
            model_name='documentoformalizacaodemanda',
            name='pca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfds', to='pca.planocontratacaoanual'),
        ),
        migrations.AlterUniqueTogether(
            name='planocontratacaoanual',
            unique_together={('orgao', 'exercicio')},
        ),
    ]
