# Generated by Django 5.2.3 on 2026-06-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempca',
            name='item_dependente',
        ),
        migrations.RemoveField(
            model_name='itempca',
            name='tipo_contratacao',
        ),
        migrations.AddField(
            model_name='itempca',
            name='codigo_pca',
            field=models.CharField(blank=True, help_text='Gerado automaticamente no formato PCA-XXXX-AAAA', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='itempca',
            name='data_conclusao_efetiva',
            field=models.DateField(blank=True, help_text='Data de conclusão com contrato assinado', null=True),
        ),
        migrations.AddField(
            model_name='itempca',
            name='data_envio_pgea',
            field=models.DateField(blank=True, help_text='Data de encaminhamento ao fluxo administrativo (PGEA)', null=True),
        ),
        migrations.AddField(
            model_name='itempca',
            name='data_finalizacao_licitacao',
            field=models.DateField(blank=True, help_text='Data efetiva de finalização do certame licitatório', null=True),
        ),
        migrations.AddField(
            model_name='itempca',
            name='item_pai',
            field=models.ForeignKey(blank=True, help_text='Preenchido apenas em suspensões parciais — aponta para o item original (pai)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_filhos', to='pca.itempca'),
        ),
        migrations.AddField(
            model_name='itempca',
            name='modalidade',
            field=models.CharField(choices=[('pregao_eletronico', 'Pregão Eletrônico'), ('concorrencia', 'Concorrência'), ('concurso', 'Concurso'), ('dispensa', 'Contratação Direta — Dispensa (art. 75 NLLC)'), ('inexigibilidade', 'Contratação Direta — Inexigibilidade (art. 74 NLLC)'), ('arp_propria', 'ARP Própria (MPPI como gerenciador)'), ('arp_carona', 'ARP Carona (adesão a ARP de outro órgão)')], default='pregao_eletronico', max_length=20),
        ),
        migrations.AddField(
            model_name='itempca',
            name='normativo',
            field=models.CharField(choices=[('14133_2021', 'Lei 14.133/2021 (NLLC)'), ('8666_1993', 'Lei 8.666/1993 (transitório)')], default='14133_2021', help_text='Normativo regente da contratação', max_length=15),
        ),
        migrations.AddField(
            model_name='itempca',
            name='status',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('iniciado', 'Iniciado'), ('em_diligencia', 'Em Diligência'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('suspenso', 'Suspenso')], default='nao_iniciado', max_length=20),
        ),
        migrations.AddField(
            model_name='itempca',
            name='tipo_demanda',
            field=models.CharField(choices=[('nova', 'Nova Contratação'), ('renovacao', 'Renovação de Contrato'), ('aditivo', 'Termo Aditivo'), ('apostilamento', 'Apostilamento'), ('repactuacao', 'Repactuação'), ('indeterminado', 'Indeterminado')], default='nova', max_length=20),
        ),
        migrations.AddField(
            model_name='itempca',
            name='unidade_orcamentaria',
            field=models.CharField(choices=[('pgj', 'PGJ — Procuradoria-Geral de Justiça'), ('fmmp', 'FMMP — Fundo de Modernização do Ministério Público'), ('fepdc', 'FEPDC — Fundo Estadual de Proteção e Defesa do Consumidor')], default='pgj', help_text='Unidade orçamentária responsável pelo recurso (PGJ, FMMP ou FEPDC)', max_length=10),
        ),
        migrations.AddField(
            model_name='itempca',
            name='valor_empenhado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor efetivamente empenhado — atualizado conforme execução orçamentária', max_digits=16),
        ),
        migrations.AlterField(
            model_name='documentoformalizacaodemanda',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado ao setor de licitações'), ('aprovado', 'Aprovado'), ('devolvido', 'Devolvido para adequação'), ('suspensa', 'Suspensa')], default='rascunho', max_length=15),
        ),
    ]
