# Generated by Django 6.0.6 on 2026-06-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0007_conformidade_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcatalogo',
            options={'ordering': ['classificacao', 'descricao_padrao'], 'verbose_name': 'Item do Catalogo', 'verbose_name_plural': 'Catalogo de Itens'},
        ),
        migrations.AlterField(
            model_name='itemcatalogo',
            name='base_normativa',
            field=models.CharField(blank=True, help_text='Ex: Art. 3, I — Ato PGJ 1.415/2024', max_length=150),
        ),
        migrations.AlterField(
            model_name='orcamentoplanejado',
            name='trava_ativa',
            field=models.BooleanField(default=False, help_text='Quando ativa, bloqueia demandas que ultrapassem o teto aprovado', verbose_name='Trava ativa'),
        ),
        migrations.AlterField(
            model_name='orcamentoplanejado',
            name='valor_fepdc',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor aprovado com recursos do FEPDC', max_digits=16, verbose_name='Teto FEPDC'),
        ),
        migrations.AlterField(
            model_name='orcamentoplanejado',
            name='valor_fmmp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor aprovado com recursos do FMMP', max_digits=16, verbose_name='Teto FMMP'),
        ),
        migrations.AlterField(
            model_name='orcamentoplanejado',
            name='valor_pgj',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor aprovado com recursos da Procuradoria-Geral de Justica', max_digits=16, verbose_name='Teto PGJ'),
        ),
        migrations.AlterField(
            model_name='planocontratacaoanual',
            name='status',
            field=models.CharField(choices=[('coleta', 'Coleta de demandas (10-30 jul)'), ('consolidacao', 'Consolidação CLC + APG (1-20 ago)'), ('aprovacao', 'Aguardando aprovação PGJ'), ('aprovado', 'Aprovado pelo PGJ'), ('publicado_pncp', 'Publicado no PNCP'), ('revisao_out', 'Em revisão (1-30 out)'), ('revisao_loa', 'Em revisão pós-LOA')], default='coleta', max_length=20),
        ),
    ]
