# Generated by Django 5.2.3 on 2026-07-08 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0011_categoria_granular_contrato_vigente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conformidadeitem',
            options={'verbose_name': 'Conformidade do Item', 'verbose_name_plural': 'Conformidade dos Itens'},
        ),
        migrations.AlterField(
            model_name='conformidadeitem',
            name='avaliado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conformidades_avaliadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricoFasePCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_status', models.CharField(choices=[('coleta', 'Coleta de demandas (10-30 jul)'), ('consolidacao', 'Consolidação CLC + APG (1-20 ago)'), ('aprovacao', 'Aguardando aprovação PGJ'), ('aprovado', 'Aprovado pelo PGJ'), ('publicado_pncp', 'Publicado no PNCP'), ('revisao_out', 'Em revisão (1-30 out)'), ('revisao_loa', 'Em revisão pós-LOA')], max_length=20)),
                ('para_status', models.CharField(choices=[('coleta', 'Coleta de demandas (10-30 jul)'), ('consolidacao', 'Consolidação CLC + APG (1-20 ago)'), ('aprovacao', 'Aguardando aprovação PGJ'), ('aprovado', 'Aprovado pelo PGJ'), ('publicado_pncp', 'Publicado no PNCP'), ('revisao_out', 'Em revisão (1-30 out)'), ('revisao_loa', 'Em revisão pós-LOA')], max_length=20)),
                ('observacao', models.TextField(blank=True, help_text='Justificativa da mudança de fase (obrigatória ao recuar)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_fases', to='pca.planocontratacaoanual')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mudancas_fase_pca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Fase do PCA',
                'verbose_name_plural': 'Históricos de Fase do PCA',
                'ordering': ['-criado_em'],
            },
        ),
    ]
