# Generated by Django 5.2.3 on 2026-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0012_alter_conformidadeitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcatalogo',
            name='descricao_detalhada',
            field=models.TextField(blank=True, help_text='Especificação completa do item (catálogo interno 2027).'),
        ),
        migrations.AddField(
            model_name='itemcatalogo',
            name='grupo',
            field=models.CharField(blank=True, db_index=True, help_text='Grupo do catálogo interno (ex: Copa e Cozinha, Informática - Equipamentos).', max_length=100),
        ),
        migrations.AddField(
            model_name='itemcatalogo',
            name='valor_referencia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor unitário de referência do catálogo interno.', max_digits=14, null=True),
        ),
    ]
