# Generated by Django 5.2.3 on 2026-07-21 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0013_itemcatalogo_descricao_detalhada_itemcatalogo_grupo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itempca',
            name='analisado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itempca',
            name='analisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pca_analisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itempca',
            name='motivo_analise',
            field=models.TextField(blank=True, help_text='Justificativa da decisão — obrigatória em aprovação parcial (o que foi cortado e por quê) e em não aprovação.'),
        ),
        migrations.AddField(
            model_name='itempca',
            name='quantidade_solicitada',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Quantidade originalmente pedida pela unidade, preservada quando a análise reduz `quantidade_estimada` (aprovação parcial).', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='itempca',
            name='status_aprovacao',
            field=models.CharField(choices=[('pendente', 'Pendente de análise'), ('aprovada_integral', 'Aprovada integralmente'), ('aprovada_parcial', 'Aprovada parcialmente'), ('nao_aprovada', 'Não aprovada')], db_index=True, default='pendente', help_text='Resultado da análise da área gestora sobre esta demanda.', max_length=20),
        ),
        migrations.AddField(
            model_name='itempca',
            name='valor_unitario_solicitado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor unitário originalmente pedido, preservado na aprovação parcial.', max_digits=14, null=True),
        ),
    ]
