# Generated by Django 5.2.3 on 2026-08-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0014_itempca_analisado_em_itempca_analisado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempca',
            name='modalidade',
            field=models.CharField(choices=[('pregao_eletronico', 'Pregão Eletrônico'), ('concorrencia', 'Concorrência'), ('concurso', 'Concurso'), ('credenciamento', 'Credenciamento (art. 79 NLLC)'), ('dispensa', 'Contratação Direta — Dispensa (art. 75 NLLC)'), ('inexigibilidade', 'Contratação Direta — Inexigibilidade (art. 74 NLLC)'), ('arp_propria', 'ARP Própria (MPPI como gerenciador)'), ('arp_carona', 'ARP Carona (adesão a ARP de outro órgão)')], default='pregao_eletronico', max_length=20),
        ),
    ]
