# Generated by Django 5.2.3 on 2026-08-14 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0015_alter_itempca_modalidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoDataItemPCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('data_pretendida_conclusao', 'Conclusão prevista'), ('data_envio_pgea', 'Envio ao PGEA'), ('data_finalizacao_licitacao', 'Finalização da licitação'), ('data_conclusao_efetiva', 'Conclusão efetiva')], max_length=40)),
                ('de_data', models.DateField(blank=True, null=True)),
                ('para_data', models.DateField(blank=True, null=True)),
                ('justificativa', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_datas', to='pca.itempca')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mudancas_data_pca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Data do Item',
                'verbose_name_plural': 'Históricos de Datas dos Itens',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['item', '-criado_em'], name='pca_histori_item_id_1f200b_idx')],
            },
        ),
    ]
