# Generated by Django 5.2.3 on 2026-08-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0016_historicodataitempca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempca',
            name='etp',
        ),
    ]
