# Generated by Django 5.2.3 on 2026-06-24 14:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARPExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_gerenciador_nome', models.CharField(help_text='Nome do órgão que originou a ARP', max_length=255)),
                ('orgao_gerenciador_cnpj', models.CharField(max_length=18)),
                ('numero_arp_origem', models.CharField(help_text='Número da ARP no órgão gerenciador', max_length=30)),
                ('numero_pncp_origem', models.CharField(blank=True, help_text='Identificador PNCP da ARP de origem', max_length=100)),
                ('objeto', models.TextField()),
                ('fornecedor_razao_social', models.CharField(max_length=255)),
                ('fornecedor_cnpj_cpf', models.CharField(max_length=18)),
                ('data_inicio_vigencia', models.DateField()),
                ('data_fim_vigencia', models.DateField()),
                ('numero_sei_adesao', models.CharField(blank=True, help_text='Número do processo SEI/MPPI de adesão', max_length=30)),
                ('quantidade_autorizada', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_total_autorizado', models.DecimalField(decimal_places=2, max_digits=16)),
                ('quantidade_utilizada', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='ativa', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arps_externas_criadas', to=settings.AUTH_USER_MODEL)),
                ('unidade_beneficiaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arps_externas', to='core.unidaderequisitante')),
            ],
            options={
                'verbose_name': 'ARP Externa (Carona Recebida)',
                'verbose_name_plural': 'ARPs Externas (Caronas Recebidas)',
                'ordering': ['-data_inicio_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='AtaRegistroPrecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_arp', models.CharField(help_text='Número sequencial da ARP no exercício (ex: 001/2027)', max_length=30)),
                ('numero_sei', models.CharField(blank=True, help_text='Número do processo SEI/MPPI (obrigatório para rastreabilidade)', max_length=30)),
                ('numero_pncp', models.CharField(blank=True, help_text='Identificador de publicação no PNCP (condição de eficácia — art. 174 NLLC)', max_length=100)),
                ('objeto', models.TextField()),
                ('modalidade_origem', models.CharField(choices=[('pregao_eletronico', 'Pregão Eletrônico'), ('concorrencia', 'Concorrência'), ('dispensa_srp', 'Dispensa para SRP (art. 75, §7º NLLC)')], max_length=20)),
                ('processo_licitatorio', models.CharField(blank=True, help_text='Número do processo licitatório que originou a ARP', max_length=30)),
                ('fornecedor_razao_social', models.CharField(max_length=255)),
                ('fornecedor_cnpj_cpf', models.CharField(max_length=18)),
                ('data_assinatura', models.DateField()),
                ('data_inicio_vigencia', models.DateField()),
                ('data_fim_vigencia', models.DateField(help_text='Máximo 12 meses da assinatura (Decreto 11.462/2023, art. 4º, §2º)')),
                ('data_publicacao_pncp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada'), ('encerrada', 'Encerrada (vigência expirada)')], default='vigente', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arps_criadas', to=settings.AUTH_USER_MODEL)),
                ('orgao_gerenciador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arps_gerenciadas', to='core.orgao')),
            ],
            options={
                'verbose_name': 'Ata de Registro de Preços',
                'verbose_name_plural': 'Atas de Registro de Preços',
                'ordering': ['-data_inicio_vigencia'],
                'unique_together': {('orgao_gerenciador', 'numero_arp')},
            },
        ),
        migrations.CreateModel(
            name='ItemARP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('codigo_catmat_catser', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField()),
                ('unidade_fornecimento', models.CharField(max_length=30)),
                ('quantidade_registrada', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantidade_contratada', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('quantidade_cedida_carona', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Total cedido a órgãos aderentes via carona', max_digits=14)),
                ('arp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='srp.ataregistroprecos')),
            ],
            options={
                'verbose_name': 'Item de ARP',
                'ordering': ['numero_item'],
                'unique_together': {('arp', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='ContratacaoDecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=30)),
                ('numero_sei', models.CharField(blank=True, max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('data_emissao', models.DateField()),
                ('data_entrega_prevista', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('emitido', 'Emitido'), ('em_execucao', 'Em execução'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='emitido', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratacoes_decorrentes', to='srp.ataregistroprecos')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratacoes_decorrentes_criadas', to=settings.AUTH_USER_MODEL)),
                ('unidade_requisitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratacoes_decorrentes', to='core.unidaderequisitante')),
                ('item_arp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratacoes', to='srp.itemarp')),
            ],
            options={
                'verbose_name': 'Contratação Decorrente de ARP',
                'verbose_name_plural': 'Contratações Decorrentes de ARP',
            },
        ),
        migrations.CreateModel(
            name='AdesaoARP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_aderente_nome', models.CharField(max_length=255)),
                ('orgao_aderente_cnpj', models.CharField(max_length=18)),
                ('quantidade_solicitada', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('data_solicitacao', models.DateField()),
                ('data_autorizacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('autorizada', 'Autorizada'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=15)),
                ('numero_sei_autorizacao', models.CharField(blank=True, max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adesoes_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('arp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adesoes', to='srp.ataregistroprecos')),
                ('item_arp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adesoes', to='srp.itemarp')),
            ],
            options={
                'verbose_name': 'Adesão à ARP (Carona Cedida)',
                'verbose_name_plural': 'Adesões à ARP (Caronas Cedidas)',
            },
        ),
    ]
