# Generated by Django 6.0.6 on 2026-06-23 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('core', '0001_initial'),
        ('licitacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARPExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_gerenciador_nome', models.CharField(max_length=255)),
                ('orgao_gerenciador_cnpj', models.CharField(max_length=18)),
                ('numero_ata_externa', models.CharField(max_length=30)),
                ('ano_ata_externa', models.PositiveSmallIntegerField()),
                ('objeto', models.TextField()),
                ('fornecedor_cnpj', models.CharField(max_length=18)),
                ('fornecedor_razao', models.CharField(max_length=255)),
                ('numero_sei_adesao_mppi', models.CharField(blank=True, help_text='Processo SEI/MPPI da adesão', max_length=30)),
                ('data_adesao', models.DateField()),
                ('data_vigencia_fim', models.DateField()),
                ('quantidade_autorizada', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_autorizado', models.DecimalField(decimal_places=2, max_digits=16)),
                ('quantidade_utilizada', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('valor_utilizado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('pncp_ata_externa_id', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ARP Externa (Carona Recebida)',
            },
        ),
        migrations.CreateModel(
            name='AtaRegistroPrecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ata', models.CharField(max_length=30)),
                ('ano', models.PositiveSmallIntegerField()),
                ('objeto', models.TextField()),
                ('fornecedor_cnpj', models.CharField(max_length=18)),
                ('fornecedor_razao', models.CharField(max_length=255)),
                ('data_assinatura', models.DateField()),
                ('data_vigencia_inicio', models.DateField()),
                ('data_vigencia_fim', models.DateField()),
                ('prorrogada', models.BooleanField(default=False)),
                ('data_prorrogacao', models.DateField(blank=True, null=True)),
                ('fundamento_prorrogacao', models.TextField(blank=True, help_text='Critérios do MJR 95/2025 e art. 12 Dec. 11.462/2023')),
                ('numero_sei', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada'), ('encerrada', 'Encerrada')], default='vigente', max_length=15)),
                ('pncp_id', models.CharField(blank=True, max_length=100)),
                ('publicada_pncp', models.BooleanField(default=False)),
                ('data_publicacao_pncp', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('orgao_gerenciador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arps_gerenciadas', to='core.orgao')),
                ('processo_licitatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arps', to='licitacao.processolicitatorio')),
            ],
            options={
                'verbose_name': 'Ata de Registro de Preços',
                'unique_together': {('orgao_gerenciador', 'numero_ata', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='AdesaoARP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_aderente_nome', models.CharField(max_length=255)),
                ('orgao_aderente_cnpj', models.CharField(max_length=18)),
                ('orgao_aderente_esfera', models.CharField(max_length=30)),
                ('numero_sei_adesao', models.CharField(blank=True, help_text='Processo SEI/MPPI da solicitação de carona', max_length=30)),
                ('data_solicitacao', models.DateField()),
                ('data_autorizacao', models.DateField(blank=True, null=True)),
                ('justificativa_vantajosidade', models.TextField(help_text='Obrigatória — MJR 86/2025 e art. 28 §1º Dec. 11.462/2023')),
                ('mjr_86_observado', models.BooleanField(default=False, help_text='Confirmação de observância do MJR 86/2025')),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('autorizada', 'Autorizada pelo MPPI'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=15)),
                ('publicada_pncp', models.BooleanField(default=False)),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adesoes', to='srp.ataregistroprecos')),
            ],
        ),
        migrations.CreateModel(
            name='ContratacaoDecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=30)),
                ('numero_sei', models.CharField(blank=True, max_length=30)),
                ('data_emissao', models.DateField()),
                ('data_entrega_prevista', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='ativa', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratacoes_decorrentes', to='srp.ataregistroprecos')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratacoes_srp', to='contratos.contrato')),
                ('unidade_requisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidaderequisitante')),
            ],
        ),
        migrations.CreateModel(
            name='ItemARP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('codigo_catmat_catser', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField()),
                ('unidade_medida', models.CharField(max_length=30)),
                ('quantidade_registrada', models.DecimalField(decimal_places=4, max_digits=14)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='srp.ataregistroprecos')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAdesaoARP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=4, max_digits=14)),
                ('quantidade_autorizada', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('adesao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='srp.adesaoarp')),
                ('item_arp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adesoes', to='srp.itemarp')),
            ],
        ),
        migrations.CreateModel(
            name='ItemContratacaoDecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=14)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contratacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='srp.contratacaodecorrente')),
                ('item_arp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratacoes', to='srp.itemarp')),
            ],
        ),
    ]
