# Generated by Django 5.2.3 on 2026-06-24 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0002_initial'),
        ('srp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoPCAItemARP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_comprometida', models.DecimalField(decimal_places=4, help_text='Quantidade do PCA vinculada a este item da ARP. É a demanda certa — não pode ser somada ao saldo disponível.', max_digits=14)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_pca_arp_criados', to=settings.AUTH_USER_MODEL)),
                ('item_arp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_pca', to='srp.itemarp')),
                ('item_pca', models.ForeignKey(help_text='Apenas itens marcados como SRP podem ser vinculados a uma ARP', limit_choices_to={'is_srp': True}, on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_arp', to='pca.itempca')),
            ],
            options={
                'verbose_name': 'Vínculo PCA × ARP',
                'verbose_name_plural': 'Vínculos PCA × ARP',
                'unique_together': {('item_pca', 'item_arp')},
            },
        ),
    ]
