# Generated by Django 5.2.3 on 2026-06-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0002_vinculopcaitemarp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataregistroprecos',
            name='codigo_uasg_gerenciadora',
            field=models.CharField(blank=True, help_text='Código UASG do órgão gerenciador (MPPI = 926092). Necessário para consultar e sincronizar dados via API Compras.gov.br.', max_length=10),
        ),
        migrations.AddField(
            model_name='ataregistroprecos',
            name='id_compra_compras_gov',
            field=models.CharField(blank=True, help_text='Identificador único da compra no Compras.gov.br (campo idCompra da API)', max_length=100),
        ),
        migrations.AddField(
            model_name='ataregistroprecos',
            name='importada_da_api',
            field=models.BooleanField(default=False, help_text='Indica se a ARP foi importada automaticamente via API Compras.gov.br'),
        ),
        migrations.AddField(
            model_name='ataregistroprecos',
            name='numero_controle_pncp_ata',
            field=models.CharField(blank=True, help_text='Número de controle da ata no PNCP (retornado pela API Compras.gov.br)', max_length=100),
        ),
        migrations.AddField(
            model_name='itemarp',
            name='banco_referencia',
            field=models.CharField(blank=True, choices=[('catmat', 'CATMAT (Catálogo de Materiais)'), ('catser', 'CATSER (Catálogo de Serviços)'), ('sinapi', 'SINAPI (Sistema Nacional de Pesquisa de Custos)'), ('orse', 'ORSE (Orçamento de Obras e Serviços de Engenharia)'), ('outro', 'Outro')], help_text='Banco de preços de referência utilizado (SINAPI, ORSE, CATMAT, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='itemarp',
            name='codigo_item_compras_gov',
            field=models.IntegerField(blank=True, help_text='codigoItem retornado pela API Compras.gov.br (código PDM/CATMAT numérico)', null=True),
        ),
        migrations.AddField(
            model_name='itemarp',
            name='codigo_referencia_banco',
            field=models.CharField(blank=True, help_text='Código de referência em banco de custos (ex: código SINAPI 91871, ORSE 9718)', max_length=30),
        ),
        migrations.AddField(
            model_name='itemarp',
            name='importado_da_api',
            field=models.BooleanField(default=False, help_text='Indica se o item foi importado via API Compras.gov.br'),
        ),
        migrations.AddField(
            model_name='itemarp',
            name='maximo_adesao_api',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Quantidade máxima para adesão (carona) conforme API Compras.gov.br. Se zero, carona não está liberada no sistema — exige SEI de autorização.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='itemarp',
            name='numero_lote',
            field=models.CharField(blank=True, help_text='Número do lote ao qual o item pertence (ex: Lote 1, Lote 2)', max_length=20),
        ),
    ]
