# Generated by Django 5.2.3 on 2026-06-24 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0003_api_compras_integracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoComprasnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_comprasnet_id', models.IntegerField(help_text='ID interno do contrato na API Comprasnet Contratos', unique=True)),
                ('numero', models.CharField(help_text='Número do contrato (ex: 00005/2026)', max_length=30)),
                ('objeto', models.TextField(blank=True)),
                ('fornecedor_nome', models.CharField(blank=True, max_length=255)),
                ('fornecedor_cnpj', models.CharField(blank=True, max_length=18)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_global', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_acumulado', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('data_assinatura', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, default='Ativo', max_length=20)),
                ('modalidade', models.CharField(blank=True, max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('licitacao_numero', models.CharField(blank=True, help_text='Número do pregão/licitação que originou o contrato', max_length=30)),
                ('processo', models.CharField(blank=True, max_length=60)),
                ('uasg', models.CharField(blank=True, max_length=10)),
                ('importado_em', models.DateTimeField(auto_now=True)),
                ('arp', models.ForeignKey(blank=True, help_text='ARP da qual este contrato é decorrente (se identificada)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_comprasnet', to='srp.ataregistroprecos')),
            ],
            options={
                'verbose_name': 'Contrato (Comprasnet)',
                'verbose_name_plural': 'Contratos (Comprasnet)',
                'ordering': ['-data_assinatura'],
            },
        ),
        migrations.CreateModel(
            name='EmpenhoComprasnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empenho_comprasnet_id', models.IntegerField(help_text='ID interno do empenho na API Comprasnet Contratos', unique=True)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('codigo_catmat', models.CharField(blank=True, help_text='Código CATMAT/CATSER do item empenhado', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('unidade', models.CharField(blank=True, max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('uasg', models.CharField(blank=True, max_length=10)),
                ('importado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(blank=True, help_text='Contrato ao qual este empenho está vinculado (se identificado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empenhos', to='srp.contratocomprasnet')),
                ('item_arp', models.ForeignKey(blank=True, help_text='Item da ARP ao qual este empenho foi vinculado (por código catmat/catser)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empenhos_comprasnet', to='srp.itemarp')),
            ],
            options={
                'verbose_name': 'Empenho (Comprasnet)',
                'verbose_name_plural': 'Empenhos (Comprasnet)',
                'ordering': ['-data_emissao'],
            },
        ),
    ]
