# Generated by Django 5.2.15 on 2026-06-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0008_vinculoarpunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataregistroprecos',
            name='usa_lotes',
            field=models.BooleanField(default=False, help_text="Marque quando a licitação foi dividida em lotes (ex: Lote 1 – Material de Escritório, Lote 2 – Café). Desmarque para indicar lote único. Quando marcado, cada ItemARP deve ter o campo 'numero_lote' preenchido.", verbose_name='Usa lotes'),
        ),
        migrations.AddField(
            model_name='contratacaodecorrente',
            name='exercicio',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ano fiscal em que a contratação foi emitida. Permite calcular o saldo consumido por ano na ARP.', null=True, verbose_name='Exercício'),
        ),
        migrations.AddField(
            model_name='contratacaodecorrente',
            name='numero_contrato',
            field=models.CharField(blank=True, help_text='Número formal do contrato decorrente desta ARP (ex: 123/2026). Distinto do número do pedido — é o instrumento contratual assinado.', max_length=30, verbose_name='Número do contrato'),
        ),
        migrations.AlterField(
            model_name='ataregistroprecos',
            name='link_ata_pncp',
            field=models.URLField(blank=True, help_text='URL da ata no PNCP (ex: https://pncp.gov.br/app/atas/05805924000189/2024/16/1). Usada para consultar contratos e histórico via PNCP REST API.', max_length=300),
        ),
        migrations.AlterField(
            model_name='contratoarp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemcontratoarp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
