# Generated by Django 5.2.3 on 2026-07-21 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0011_itemarp_unidade_fornecimento_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacaodecorrente',
            name='link_contrato',
            field=models.URLField(blank=True, help_text='URL para visualização do instrumento contratual assinado (PNCP, SEI ou repositório do MPPI). Abre em nova aba.', verbose_name='Link do contrato assinado'),
        ),
        migrations.AddField(
            model_name='contratacaodecorrente',
            name='unidade_orcamentaria',
            field=models.CharField(blank=True, choices=[('pgj', 'PGJ — Procuradoria-Geral de Justiça'), ('fmmp', 'FMMP — Fundo de Modernização do Ministério Público'), ('fepdc', 'FEPDC — Fundo Estadual de Proteção e Defesa do Consumidor')], db_index=True, help_text='Fonte orçamentária que custeia a contratação (PGJ, FMMP ou FEPDC).', max_length=10, verbose_name='Unidade gestora / fonte'),
        ),
        migrations.AlterField(
            model_name='vinculopcaitemarp',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_pca_arp_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
