# Generated by Django 5.2.3 on 2026-07-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0012_contratacaodecorrente_link_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataregistroprecos',
            name='data_substituicao',
            field=models.DateField(blank=True, help_text='Data em que o novo detentor assumiu a ata.', null=True, verbose_name='Data da substituição'),
        ),
        migrations.AddField(
            model_name='ataregistroprecos',
            name='fornecedor_original_cnpj_cpf',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ/CPF do fornecedor original'),
        ),
        migrations.AddField(
            model_name='ataregistroprecos',
            name='fornecedor_original_razao_social',
            field=models.CharField(blank=True, help_text='Razão social de quem venceu a licitação, antes da substituição.', max_length=255, verbose_name='Fornecedor original (vencedor)'),
        ),
        migrations.AddField(
            model_name='ataregistroprecos',
            name='motivo_substituicao',
            field=models.TextField(blank=True, help_text='Ex.: desistência do vencedor, perda das condições de habilitação, cancelamento do registro do preço.', verbose_name='Motivo da substituição'),
        ),
        migrations.AddField(
            model_name='ataregistroprecos',
            name='substituido_por_cadastro_reserva',
            field=models.BooleanField(default=False, help_text='Marque quando o vencedor original desistiu e a ata passou a outro fornecedor do cadastro de reserva, com o preço deste.', verbose_name='Detentor substituído (cadastro de reserva)'),
        ),
        migrations.AlterField(
            model_name='ataregistroprecos',
            name='fornecedor_razao_social',
            field=models.CharField(help_text='Detentor ATUAL da ata. Em caso de substituição por cadastro de reserva, este é o novo detentor (o vencedor original fica em fornecedor_original_razao_social).', max_length=255),
        ),
    ]
