# Generated by Django 6.0.6 on 2026-06-23 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('licitacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=30)),
                ('ano', models.PositiveSmallIntegerField()),
                ('numero_sei', models.CharField(blank=True, help_text='Número do processo SEI/MPPI do contrato', max_length=30)),
                ('objeto', models.TextField()),
                ('contratado_cnpj', models.CharField(max_length=18)),
                ('contratado_razao', models.CharField(max_length=255)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=16)),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=16)),
                ('data_assinatura', models.DateField()),
                ('data_inicio_vigencia', models.DateField()),
                ('data_fim_vigencia', models.DateField()),
                ('is_servico_continuo', models.BooleanField(default=False)),
                ('prazo_maximo_meses', models.PositiveSmallIntegerField(blank=True, help_text='Máx. 120 meses — art. 5º Ato PGJ 1415/2024', null=True)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('suspenso', 'Suspenso'), ('rescindido', 'Rescindido'), ('encerrado', 'Encerrado')], default='vigente', max_length=15)),
                ('is_contrato_ti', models.BooleanField(default=False)),
                ('pncp_id', models.CharField(blank=True, max_length=100)),
                ('publicado_pncp', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fiscal_adm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_fiscal_adm', to=settings.AUTH_USER_MODEL)),
                ('fiscal_requisitante_ti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_fiscal_req_ti', to=settings.AUTH_USER_MODEL)),
                ('fiscal_tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_fiscal_tecnico', to=settings.AUTH_USER_MODEL)),
                ('gestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_geridos', to=settings.AUTH_USER_MODEL)),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('processo_licitatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licitacao.processolicitatorio')),
            ],
            options={
                'unique_together': {('orgao', 'numero_contrato', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Apostilamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('numero_sei', models.CharField(blank=True, max_length=30)),
                ('novo_indice_reajuste', models.CharField(blank=True, max_length=50)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostilamentos', to='contratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('prazo', 'Prorrogação de prazo'), ('valor', 'Acréscimo de valor'), ('prazo_valor', 'Prazo e valor'), ('supressao', 'Supressão'), ('objeto', 'Alteração de objeto')], max_length=20)),
                ('data_assinatura', models.DateField()),
                ('novo_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('nova_data_fim', models.DateField(blank=True, null=True)),
                ('fundamento_legal', models.CharField(max_length=100)),
                ('justificativa', models.TextField()),
                ('numero_sei', models.CharField(blank=True, max_length=30)),
                ('pncp_id', models.CharField(blank=True, max_length=100)),
                ('publicado_pncp', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='contratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemFornecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('data_emissao', models.DateField()),
                ('data_entrega_prevista', models.DateField()),
                ('data_atendimento', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('emitida', 'Emitida'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='emitida', max_length=15)),
                ('volume_servico', models.TextField(blank=True, help_text='Pontos de função, sprints, horas etc.')),
                ('cronograma_execucao', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_fornecimento', to='contratos.contrato')),
                ('responsavel_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oss_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
