# Generated by Django 5.2.3 on 2026-06-24 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('srp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aditivo', models.PositiveIntegerField()),
                ('numero_sei', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(choices=[('prazo', 'Prorrogação de Prazo'), ('valor', 'Acréscimo de Valor'), ('supressao', 'Supressão de Valor'), ('prazo_valor', 'Prazo e Valor'), ('objeto', 'Alteração de Objeto')], max_length=15)),
                ('fundamento_legal', models.CharField(default='art. 124 NLLC (Lei 14.133/2021)', help_text='Fundamento legal do aditivo', max_length=100)),
                ('data_assinatura', models.DateField()),
                ('nova_data_fim_vigencia', models.DateField(blank=True, help_text='Preenchido quando o aditivo altera o prazo', null=True)),
                ('valor_acrescimo', models.DecimalField(decimal_places=2, default=0, help_text='Positivo para acréscimo, negativo para supressão', max_digits=16)),
                ('percentual_acrescimo', models.DecimalField(decimal_places=2, default=0, help_text='Percentual sobre o valor inicial do contrato', max_digits=5)),
                ('numero_pncp', models.CharField(blank=True, max_length=100)),
                ('objeto_aditivo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Termo Aditivo',
                'verbose_name_plural': 'Termos Aditivos',
                'ordering': ['numero_aditivo'],
            },
        ),
        migrations.CreateModel(
            name='Apostilamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apostilamento', models.PositiveIntegerField()),
                ('numero_sei', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(choices=[('reajuste', 'Reajuste por Índice'), ('repactuacao', 'Repactuação (serviços contínuos)'), ('atualizacao_monetaria', 'Atualização Monetária'), ('correcao_erro', 'Correção de Erro Material')], max_length=25)),
                ('fundamento_legal', models.CharField(default='art. 136 NLLC (Lei 14.133/2021)', max_length=100)),
                ('data_apostilamento', models.DateField()),
                ('indice_aplicado', models.CharField(blank=True, help_text='Ex: IPCA, INPC, IPC-A', max_length=20)),
                ('percentual_reajuste', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=16)),
                ('valor_novo', models.DecimalField(decimal_places=2, max_digits=16)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apostilamento',
                'ordering': ['numero_apostilamento'],
            },
        ),
        migrations.CreateModel(
            name='OrdemFornecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordem', models.CharField(max_length=30)),
                ('numero_sei', models.CharField(blank=True, max_length=30)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16)),
                ('data_emissao', models.DateField()),
                ('data_prazo_execucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('emitida', 'Emitida'), ('em_execucao', 'Em execução'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='emitida', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ordem de Fornecimento / Serviço',
                'verbose_name_plural': 'Ordens de Fornecimento / Serviço',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=30)),
                ('numero_sei', models.CharField(blank=True, help_text='Processo SEI/MPPI (campo obrigatório para rastreabilidade institucional)', max_length=30)),
                ('numero_pncp', models.CharField(blank=True, help_text='Publicação no PNCP — condição de eficácia (art. 174 NLLC)', max_length=100)),
                ('tipo', models.CharField(choices=[('fornecimento', 'Fornecimento de Bens'), ('servico_continuo', 'Serviço de Execução Continuada (Ato PGJ 1415/2024)'), ('servico_nao_continuo', 'Serviço de Execução Não Continuada'), ('obra', 'Obras e Serviços de Engenharia'), ('locacao', 'Locação de Imóvel'), ('solucao_ti', 'Solução de TIC (Res. CNMP 283/2024)')], max_length=25)),
                ('objeto', models.TextField()),
                ('contratado_razao_social', models.CharField(max_length=255)),
                ('contratado_cnpj_cpf', models.CharField(max_length=18)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=16)),
                ('valor_atual', models.DecimalField(decimal_places=2, help_text='Atualizado automaticamente após aditivos de valor', max_digits=16)),
                ('saldo_disponivel', models.DecimalField(decimal_places=2, help_text='Saldo restante após ordens de fornecimento / medições', max_digits=16)),
                ('data_assinatura', models.DateField()),
                ('data_inicio_vigencia', models.DateField()),
                ('data_fim_vigencia', models.DateField()),
                ('data_publicacao_pncp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('suspenso', 'Suspenso'), ('rescindido', 'Rescindido'), ('encerrado', 'Encerrado')], default='vigente', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arp_externa_origem', models.ForeignKey(blank=True, help_text='Preenchido quando o contrato decorre de carona em ARP de outro órgão', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_mppi', to='srp.arpexterna')),
                ('arp_origem', models.ForeignKey(blank=True, help_text='Preenchido quando o contrato decorre de ARP própria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_decorrentes', to='srp.ataregistroprecos')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_criados', to=settings.AUTH_USER_MODEL)),
                ('fiscal_administrativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_fiscalizados_adm', to=settings.AUTH_USER_MODEL)),
                ('fiscal_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_fiscalizados_tec', to=settings.AUTH_USER_MODEL)),
                ('gestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_geridos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'ordering': ['-data_assinatura'],
            },
        ),
    ]
