# Generated by Django 5.2.3 on 2026-06-24 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('core', '0001_initial'),
        ('pca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='item_pca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='pca.itempca'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.orgao'),
        ),
        migrations.AddField(
            model_name='apostilamento',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostilamentos', to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='aditivo',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='ordemfornecimento',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_fornecimento', to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='ordemfornecimento',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemfornecimento',
            name='unidade_requisitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_fornecimento', to='core.unidaderequisitante'),
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('orgao', 'numero_contrato')},
        ),
        migrations.AlterUniqueTogether(
            name='apostilamento',
            unique_together={('contrato', 'numero_apostilamento')},
        ),
        migrations.AlterUniqueTogether(
            name='aditivo',
            unique_together={('contrato', 'numero_aditivo')},
        ),
    ]
