# Generated by Django 5.2.3 on 2026-06-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='ultima_atualizacao_siafe',
            field=models.DateTimeField(blank=True, help_text='Última sincronização com o SIAFE-PI', null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_empenhado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total empenhado no SIAFE vinculado a este contrato', max_digits=16),
        ),
    ]
