# Generated by Django 5.2.3 on 2026-06-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contrato_ultima_atualizacao_siafe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='codigo_siafe',
            field=models.CharField(blank=True, db_index=True, help_text='Número automático do contrato no SIAFE-PI (ex: 26100674)', max_length=12),
        ),
    ]
