# Generated by Django 5.2.3 on 2026-06-30 02:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_contrato_unidade_requisitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empenho', models.CharField(help_text='Número da Nota de Empenho no SIAFE (ex: 2025NE00099)', max_length=30)),
                ('ano_exercicio', models.PositiveSmallIntegerField(default=2025)),
                ('natureza', models.CharField(choices=[('ordinario', 'Ordinário'), ('estimativo', 'Estimativo'), ('global', 'Global')], default='ordinario', max_length=15)),
                ('tipo', models.CharField(choices=[('empenho', 'Empenho'), ('reforco', 'Reforço'), ('anulacao', 'Anulação')], default='empenho', max_length=10)),
                ('valor_empenhado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('valor_liquidado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('programa_trabalho', models.CharField(blank=True, help_text='PTRES / Programa de Trabalho SIAFE', max_length=30)),
                ('elemento_despesa', models.CharField(blank=True, help_text='Elemento de despesa (ex: 3.3.90.39)', max_length=20)),
                ('fonte_recurso', models.CharField(blank=True, help_text='Fonte/Destinação de Recurso (ex: 0100)', max_length=10)),
                ('unidade_orcamentaria', models.CharField(blank=True, help_text='UO no SIAFE', max_length=10)),
                ('cnpj_favorecido', models.CharField(blank=True, max_length=18)),
                ('nome_favorecido', models.CharField(blank=True, max_length=255)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_liquidacao', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do objeto no empenho SIAFE')),
                ('status_liquidacao', models.CharField(choices=[('nao_liquidado', 'Não Liquidado'), ('parcialmente', 'Parcialmente Liquidado'), ('liquidado', 'Liquidado'), ('pago', 'Pago')], default='nao_liquidado', max_length=15)),
                ('importado_siafe', models.BooleanField(default=False, help_text='Dados importados automaticamente do SIAFE')),
                ('importado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(help_text='Contrato ao qual este empenho está vinculado', on_delete=django.db.models.deletion.CASCADE, related_name='empenhos', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Empenho',
                'verbose_name_plural': 'Empenhos',
                'ordering': ['-ano_exercicio', '-numero_empenho'],
                'unique_together': {('contrato', 'numero_empenho')},
            },
        ),
    ]
