# Generated by Django 5.2.3 on 2026-07-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_empenho'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='comprasnet_id',
            field=models.PositiveIntegerField(blank=True, help_text='Identificador do contrato em contratos.comprasnet.gov.br (para sincronizações).', null=True, verbose_name='ID no Comprasnet Contratos'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='link_contrato',
            field=models.URLField(blank=True, help_text='URL do instrumento contratual assinado (PDF no Comprasnet/SEI/PNCP). Preenchido automaticamente pelo comando importar_links_contratos.', verbose_name='Link do contrato assinado'),
        ),
    ]
