# Generated by Django 5.2.3 on 2026-07-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_contrato_comprasnet_id_contrato_link_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='unidade_orcamentaria',
            field=models.CharField(blank=True, choices=[('pgj', 'PGJ — Procuradoria-Geral de Justiça'), ('fmmp', 'FMMP — Fundo de Modernização do Ministério Público'), ('fepdc', 'FEPDC — Fundo Estadual de Proteção e Defesa do Consumidor')], db_index=True, help_text='Fonte orçamentária do contrato. Pode ser inferida do sufixo do número (ex: 05/2026/FPDC) pelo comando inferir_fonte_contratos.', max_length=10, verbose_name='Unidade gestora / fonte'),
        ),
    ]
