# Generated by Django 5.2.3 on 2026-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_contrato_unidade_orcamentaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='arquivo_instrumento',
            field=models.FileField(blank=True, help_text='Upload manual do PDF do instrumento contratual assinado, para contratos sem link automático no Comprasnet (ex: fundos FPDC/FEPDC, contratos com instrumento apenas no SEI). Tem prioridade sobre link_contrato quando preenchido.', null=True, upload_to='contratos/instrumentos/%Y/', verbose_name='PDF do instrumento (upload manual)'),
        ),
    ]
