# Generated by Django 5.2.3 on 2026-07-23 12:34

from django.db import migrations, models


def seed_fepdc_2026(apps, schema_editor):
    PaginaContratosMPPI = apps.get_model("contratos", "PaginaContratosMPPI")
    PaginaContratosMPPI.objects.get_or_create(
        unidade_orcamentaria="fepdc",
        ano=2026,
        defaults={
            "url": (
                "https://www.mppi.mp.br/internet/coordenadoria-de-licitacoes-e-contratos/"
                "contratos-e-equivalentes/?sub=2026-contratos-informacoes-anteriores-a-"
                "resolucao-cnmp-no-86-2012:fepdc-2026-contratos-informacoes-anteriores-a-"
                "resolucao-cnmp-no-86-2012:contratos-fepdc-2026-contratos-informacoes-"
                "anteriores-a-resolucao-cnmp-no-86-2012"
            ),
            "observacao": "Confirmada manualmente por Thiago em 2026-07-23 para o contrato 24/2026/FEPDC.",
        },
    )


def remove_seed(apps, schema_editor):
    PaginaContratosMPPI = apps.get_model("contratos", "PaginaContratosMPPI")
    PaginaContratosMPPI.objects.filter(unidade_orcamentaria="fepdc", ano=2026).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_contrato_arquivo_instrumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaContratosMPPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_orcamentaria', models.CharField(choices=[('pgj', 'PGJ — Procuradoria-Geral de Justiça'), ('fmmp', 'FMMP — Fundo de Modernização do Ministério Público'), ('fepdc', 'FEPDC — Fundo Estadual de Proteção e Defesa do Consumidor')], max_length=10, verbose_name='Unidade gestora / fonte')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('url', models.URLField(max_length=500, verbose_name='URL da página de listagem no site do MPPI')),
                ('observacao', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Página de contratos MPPI (fallback manual)',
                'verbose_name_plural': 'Páginas de contratos MPPI (fallback manual)',
                'ordering': ['-ano', 'unidade_orcamentaria'],
                'unique_together': {('unidade_orcamentaria', 'ano')},
            },
        ),
        migrations.RunPython(seed_fepdc_2026, remove_seed),
    ]
