# Generated by Django 5.2.3 on 2026-08-17 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_empenhoproduto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações gerais da auditoria sobre este contrato.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_atualizados', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Checklist de Conformidade',
                'verbose_name_plural': 'Checklists de Conformidade',
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=50)),
                ('marcado', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('marcado_em', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos.checklistconformidade')),
                ('marcado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_checklist_marcados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item do Checklist',
                'verbose_name_plural': 'Itens do Checklist',
                'ordering': ('chave',),
                'unique_together': {('checklist', 'chave')},
            },
        ),
    ]
